---
- name: Install packages
  apt: name={{ item }} state=present update_cache=yes
  with_items:
    - libxml2-dev
    - libsnmp-dev
    - libcurl4-gnutls-dev
    - snmp-mibs-downloader

- name: Install MySQL
  apt: name={{ item }} state=present update_cache=yes
  with_items:
    - mysql-server      
    - libmysqlclient-dev
    - python-mysqldb    
    - php5-mysql
  when: zabbix3server_db_install and zabbix3server_db == "mysql"

- name: Install Apache
  apt: name={{ item }} state=present update_cache=yes
  with_items:
    - apache2
    - php5
    - php5-gd
  when: zabbix3server_web_install and zabbix3server_web == "apache"
