---
- name: Change MySQL root password
  mysql_user: name=root host={{ item }} password={{ zabbix3server_dbrootpassword }}
  with_items:
    - 127.0.0.1
    - ::1      
    - localhost

- name: Create my.cnf with root credentials
  template: src=my.cnf.j2 dest=~/.my.cnf

- name: Create MySQL DB
  mysql_db: name={{ zabbix3server_dbname }} state=present
  register: create_db

- name: Import MySQL DB
  mysql_db: name={{ zabbix3server_dbname }} state=import target={{ item }}
  with_items:
    - "{{ zabbix3server_tar.dest | dirname }}/zabbix-{{ zabbix3server_betaversion }}/database/mysql/schema.sql"
    - "{{ zabbix3server_tar.dest | dirname }}/zabbix-{{ zabbix3server_betaversion }}/database/mysql/images.sql"
    - "{{ zabbix3server_tar.dest | dirname }}/zabbix-{{ zabbix3server_betaversion }}/database/mysql/data.sql"
  when: create_db.changed != False

- name: Grant privileges to MySQL DB
#  mysql_user: name={{ zabbix3server_dbuser }} password={{ zabbix3server_dbuserpassword }} priv:{{ zabbix3server_dbname }}.*:GRANT state=present
#  the above is not working in Ansible 2.0.0.2 (issue #14062), for now, use the below
  command: mysql -u root -e 'grant all privileges on {{ zabbix3server_dbname }}.* to {{ zabbix3server_dbuser }}@{{ zabbix3server_dbhost }} identified by "{{ zabbix3server_dbuserpassword }}";'

