---
- name: Download Zabbix3
  get_url: url={{ zabbix3server_downloadurl }} dest=/usr/src
  register: zabbix3server_tar

- name: Extract Zabbix3
  unarchive: src={{ zabbix3server_tar.dest }} dest={{ zabbix3server_tar.dest | dirname }} copy=no
  args:
  # {{ zabbix3server_tar.dest }} is the downloaded file
  # {{ zabbix3server_tar.dest | dirname }} is the download dir

- name: Create group account
  group: name={{ zabbix3server_user }} state=present

- name: Create user account
  user: name={{ zabbix3server_user }} group={{ zabbix3server_user }} createhome=no state=present

- name: Ensure presence of install_path
  file: name={{ zabbix3server_install_path }} state=directory owner=root group=root mode=0751

- name: Compile
  shell: ./configure {{ zabbix3server_compile_options }} && make install
  args:
    chdir: "{{ zabbix3server_tar.dest | dirname }}/zabbix-{{ zabbix3server_betaversion }}"
    # goes to downloaded file extracted
    creates: "{{ zabbix3server_install_path }}/sbin/zabbix_server"
    # one file that is extracted, make idempotency

- name: Copy template zabbix_server.conf
  template: src=zabbix_server.conf.j2 dest={{ zabbix3server_install_path }}/etc/zabbix_server.conf
  notify: restart zabbix_server

- name: Copy zabbix_server service file
  template: src=zabbix_server_tru64_init.j2 dest=/etc/init.d/zabbix_server owner=root group=root mode=0700
